services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - microservices

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - microservices
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - tempo
      - loki
      - prometheus
    networks:
      - microservices

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./observability/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - microservices

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    user: root
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./observability/tempo-config.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    networks:
      - microservices

  loki:
    image: grafana/loki:latest
    container_name: loki
    user: root
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./observability/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - microservices

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - microservices

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./observability/grafana:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - microservices

  gateway-api:
    image: ${DOCKER_REGISTRY-}gateway-api
    build:
      context: .
      dockerfile: Gateway/Gateway.Api/Dockerfile
    container_name: gateway-api
    depends_on:
      - otel-collector
      - user-api
      - order-api
      - notification-api
    networks:
      - microservices

  user-api:
    image: ${DOCKER_REGISTRY-}user-api
    build:
      context: .
      dockerfile: Services/UserService/User.Api/Dockerfile
    container_name: user-api
    depends_on:
      rabbitmq:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - microservices

  order-api:
    image: ${DOCKER_REGISTRY-}order-api
    build:
      context: .
      dockerfile: Services/OrderService/Order.Api/Dockerfile
    container_name: order-api 
    depends_on:
      rabbitmq:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - microservices

  notification-api:
    image: ${DOCKER_REGISTRY-}notification-api
    build:
      context: .
      dockerfile: Services/NotificationService/Notification.Api/Dockerfile
    container_name: notification-api
    depends_on:
      rabbitmq:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - microservices

volumes:
  rabbitmq-data:
  prometheus-data:
  grafana-data:
  tempo-data:
  loki-data:

networks:
  microservices:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16