services:
  sqlserver:
    ports:
      - "1433:1433"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  otel-collector:
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"

  tempo:
    ports:
      - "3200:3200"

  loki:
    ports:
      - "3100:3100"

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"

  gateway-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gateway.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd!
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ./certs/gateway:/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  user-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/user.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd!
    ports:
     - "6001:8080"
     - "6061:8081"
    volumes:
      - ./certs/user:/https:ro  

  order-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/order.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd!
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ./certs/order:/https:ro

  notification-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/notification.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd!
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ./certs/notification:/https:ro