//file="GlobalUsings.cs" >

global using Autofac;
global using Autofac.Extensions.DependencyInjection;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Options;
global using Microsoft.OpenApi.Models;
global using System.Diagnostics.CodeAnalysis;
global using System.Security.Claims;
global using System.Text;
global using MassTransit;
global using User.Domain.Common;
global using User.Api.Application.Constants;
global using User.Api.Application.Features.Account.Requests.Command;
global using User.Api.Application.Models.Response;
global using User.Domain.Enums;
global using User.Domain.Identity;
global using User.Domain.SeedWork;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using User.Domain.Configurations;
global using User.Api.Application.Features.Account.Requests.Queries;
global using User.Infrastructure.Services;
global using Microsoft.AspNetCore.Identity.Data;
global using User.Api.Application.Models.Requests;
global using User.Api.Application.Extensions;
global using User.Api.Extensions;
global using User.Infrastructure.Extensions;