<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<UserSecretsId>f1ac3e9d-a03a-41e5-a561-a28ca0cc211a</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MassTransit" Version="8.5.5" />
		<PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.5.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SendGrid" Version="9.29.3" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
		<PackageReference Include="MediatR" Version="13.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />

		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Process" Version="1.14.0-beta.2" />
		<PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.14.0-beta.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.14.0-beta.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\SystemExtensions\OpenTelemetryExtension\OpenTelemetryExtension.csproj" />
		<ProjectReference Include="..\User.Domain\User.Domain.csproj" />
		<ProjectReference Include="..\User.Infrastructure\User.Infrastructure.csproj" />
	</ItemGroup>

</Project>