<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>979740a8-1dee-4d31-954e-284fa49321b3</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
		<DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OpenTelemetry" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Api" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
		<PackageReference Include="MassTransit" Version="8.5.5" />
		<PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="7.1.2" />
		<PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
		<PackageReference Include="SendGrid" Version="9.29.3" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
		<PackageReference Include="MediatR" Version="13.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Order.Domain\Order.Domain.csproj" />
		<ProjectReference Include="..\Order.Infrastructure\Order.Infrastructure.csproj" />
	</ItemGroup>

</Project>
